### ISSUE TITLE
Remove extra elements from examples

### ISSUE THREAD

**Issue by carlosalberto** [lightstep/opentelemetry-examples#116]
Although they are helpful for us, we want to keep the examples as minimalistic as possible - hence I'd propose:

* Removing any exporters, other than the OTLP/logging ones.
* Do not include any general OTLP receivers.

Assigning initially to @nslaughter but happy to discuss if needed ;)

**Comment by nslaughter** [comment]
My initial work on this will include the extra items that I introduced in the following:

- [ ] couchbase

**Comment by nslaughter** [comment]
Completed this with the PRs which are linked. 
When reviewing other examples, the only case I saw where streamlining may be useful was `rabbitmq`, but it wasn't clear to me. So I'll ping @githubsands to have a look and either confirm it stands or update with a new PR.
